#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
name: Corey Sparks - DEM 7223 Examples

# Short bio or description (displayed in the header)
description: These are examples from my course DEM 7223 Event History Analysis

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/5359657?s=400&u=ed80263a6ae7225b31a28af0437bcde7da366358&v=4

# Your website URL (e.g. https://barryclark.github.io or https://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://coreysparks.github.io
baseurl: /DEM7223

footer-links:
  email: corey.sparks@utsa.edu
  github: coreysparks
  linkedin: corey-sparks-17b0911b/
  twitter: CoreySparks1
  
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


google_analytics: UA-38742713-2



theme: jekyll-theme-minimal